from auth.exception.error_exception import APIException

__all__ = [
    "APIException",
]
