from auth.exceptions.error_exception import APIException

__all__ = [
    "APIException",
]
